// apps/orgchart/react/src/InspectorComponent.js
import React, {useEffect, useRef, useState} from "react";

import { Inspector, Vertex } from "@jsplumbtoolkit/browser-ui"

export default function InspectorComponent({surface, onSelect}) {

    const container = useRef(null)
    const [current, setCurrent] = useState(null)
    const [inspector, setInspector] = useState(null)
    const [manager, setManager] = useState(null)
    const [reports, setReports] = useState([])

    function getImage(person) {
        return `/avatars/${person.data.img}`
    }

    function selectPerson(p) {
        onSelect(p)
    }

    useEffect(() => {

        setInspector(new Inspector({
            container:container.current,
            surface,
            renderEmptyContainer:() => {
                setCurrent(null)
                setManager(null)
                setReports([])
            },
            refresh:(obj, cb) => {
                setCurrent(obj)
                setManager(obj.getTargetEdges().map(e => e.source)[0])
                setReports(obj.getSourceEdges().map(e => e.target))
                // next tick
                setTimeout(cb)
            }
        }))

    }, [])

    function renderPersonLink(person) {
        return <a className="jtk-orgchart-inspector-person" href="#" data-id={person.data.id} onClick={() => selectPerson(person)}>
                <img src={getImage(person)} alt={person.data.name}/>
                <div>
                    {person.data.name}
                    <span>{person.data.title}</span>
                </div>
                </a>
    }


    return <div ref={container}>

        {current== null && ''}

        {current != null &&
            <div className="jtk-orgchart-inspector">

                <h1>{current.data.name}</h1>
                <h2>{current.data.title}</h2>
                {reports.length > 0 && <>
                    <h5>Reports:</h5>
                    {reports.map(r => renderPersonLink(r))}

                </>}

                {manager != null && <>

                    <h5>Reports to:</h5>
                    {renderPersonLink(manager)}

                </>}

            </div>

        }

        </div>

}

// apps/orgchart/vue3/src/components/Inspector.vue
<template>
    <div ref="container">
        <div class="jtk-orgchart-inspector" v-if="current != null">
            <h1>{{current.data.name}}</h1>
            <h2>{{current.data.title}}</h2>
            <h5 v-if="reports.length > 0">Reports:</h5>
            <a v-for="r in reports" :key="r.id" class="jtk-orgchart-inspector-person" href="#" :data-id="r.data.id" @click="selectPerson(r)">
                <img :src="getImage(r)" :alt="r.data.name"/>
                {{r.data.name}}
            </a>
            <h5 v-if="manager != null">Reports to:</h5>
            <a v-if="manager != null" class="jtk-orgchart-inspector-person" href="#" :data-id="manager.data.id" @click="selectPerson(manager)">
                <img :src="getImage(manager)" :alt="manager.data.name"/>
                {{manager.data.name}}
            </a>
        </div>
    </div>
</template>
<script>

    import { nextTick } from "vue"
    import {loadSurface} from "@jsplumbtoolkit/browser-ui-vue3";
    import { Inspector } from "@jsplumbtoolkit/browser-ui"

    function retrieveDirectReports(person){
        return person.getSourceEdges().map(e => e.target)
    }

    function getManager(person) {
        return person.getTargetEdges().map(e => e.source)[0]
    }

    export default {
        data:() => {
            return {
                current:null,
                reports:[],
                manager:null,
                inspector:null

            }
        },
        methods:{
          getImage:function(p) {
              return `/avatars/${p.data.img}`
          }
        },
        props:{
            surfaceId:String,
            selectPerson:Function
        },
        mounted() {
            loadSurface(this.surfaceId, (surface) => {

                // create an inspector. give it the container element
                // and the surface and functions to use to render an
                // empty container (no selection) and to render an editor.
                // here we toggle `currentType` and let the template draw what
                // it needs to.
                this.inspector = new Inspector({
                    container:this.$refs.container,
                    surface,
                    renderEmptyContainer:() => {
                        this.reports.length = 0
                        this.manager = null
                    },
                    refresh:(obj, cb) => {
                        this.current = obj
                        this.reports = retrieveDirectReports(obj)
                        this.manager = getManager(obj)
                        nextTick()
                    }
                })

            })
        }
    }
</script>
