// apps/chatbot/react/src/TestComponent.js
import React from "react"

import {
    uuid
} from "@jsplumbtoolkit/browser-ui"

export default function TestComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    function addChoice(){
        toolkit.addPort(vertex, {
            id:uuid(),
            label:"Result"
        })
    }

    function removeChoice(id) {
        toolkit.removePort(vertex, id)
    }

    function inspectChoice(id) {
        toolkit.setSelection(vertex.getPort(id))
    }

    return <div className="jtk-chatbot-test" data-jtk-target="true">
        <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
    {vertex.data.message}
<div className="jtk-choice-add" onClick={() => addChoice()}></div>
    {vertex.data.choices.map(c =>
    <div key={c.id}  className="jtk-chatbot-choice-option" data-jtk-source="true" data-jtk-port-type="choice" data-jtk-port={c.id} onClick={() => inspectChoice(c.id)}>
        {c.label}
    <div className="jtk-choice-delete" onClick={() => removeChoice(c.id)}></div>
        </div>

    )}
</div>

}

// apps/chatbot/svelte/components/test-component.svelte
<script>

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }

    function addTest() {
        toolkit.addPort(vertex, {
            id:uuid(),
            label:"Result"
        })
    }

    function removeTest(id) {
        toolkit.removePort(vertex, id)
    }
</script>

<div class="jtk-chatbot-test" data-jtk-target="true">
    <div class="jtk-delete" on:click={remove}></div>
{data.message}
    <div class="jtk-choice-add" on:click={addTest}></div>
{#each data.choices as choice}
        <div class="jtk-chatbot-choice-option"
             data-jtk-source="true"
             data-jtk-port-type="choice"
             data-jtk-port={choice.id}>
            {choice.label}
            <div class="jtk-choice-delete" on:click={() => removeTest(choice.id)}></div>
    </div>
{/each}
        </div>
