// apps/schema-builder/vue2/src/components/ColumnComponent.vue
<template>
    <div class="jtk-schema-table-column" :data-type="obj.datatype" :data-primary-key="obj.primaryKey" :data-jtk-port="obj.id" :data-jtk-scope="obj.datatype" data-jtk-source="true" data-jtk-target="true">
        <div class="jtk-schema-table-column-delete jtk-schema-delete" v-on:click="deleteColumn()"></div>
        <div><span>{{obj.name}}</span></div>
        <div class="jtk-schema-table-column-edit jtk-schema-edit" v-on:click="editColumn"></div>
    </div>
</template>
<script>

    export default {
        props:{
            obj:Object,
            vertex:Object
        },
        methods:{
            deleteColumn:function() {
                this.$parent.getToolkit().removePort(this.vertex, this.obj.id)
            },
            editColumn:function() {
                const column = this.vertex.getPort(this.obj.id)
                this.$parent.getToolkit().setSelection(column)
            }
        }
    }
</script>

// apps/schema-builder/react-app/src/ColumnComponent.js
import React from "react"

export default function ColumnComponent({toolkit, surface, data, vertex}) {

    const column = vertex.getPort(data.id)

    function deleteColumn() {
        toolkit.removePort(vertex, column)
    }

    function editColumn() {
        toolkit.setSelection(column)
    }

    return <>
            <div className="jtk-schema-table-column" data-type={data.datatype} data-primary-key={(data.primaryKey || false).toString()} data-jtk-port={column.id} data-jtk-scope={data.datatype} data-jtk-source={true} data-jtk-target={true}>
                <div className="jtk-schema-table-column-delete jtk-schema-delete" onClick={() => deleteColumn()}/>
                <div><span>{data.name}</span></div>
                <div className="jtk-schema-table-column-edit jtk-schema-edit" onClick={() => editColumn()}/>
        </div>
    </>
}
