// apps/hello-world/react/src/HelloWorldComponent.js
import React, { useEffect, useRef, useState } from "react";

import {
    newInstance,
    DEFAULT,
    AnchorLocations,
    BlankEndpoint,
    ArrowOverlay,
    AbsoluteLayout,
    EVENT_CANVAS_CLICK
} from "@jsplumbtoolkit/browser-ui"

import {
    JsPlumbToolkitSurfaceComponent
} from "@jsplumbtoolkit/browser-ui-react";


import HelloComponent from './HelloComponent'
import WorldComponent from './WorldComponent'


export default function HelloWorldComponent({ctx}) {

    const [msg, setMsg] = useState('')
    const surfaceComponent = useRef(null)

    const toolkit = newInstance()

    const renderParams= {
        layout:{
            // there are several layouts that ship with the toolkit.
            type:AbsoluteLayout.type,
            options:{
                //... if your chosen layout is configurable, options go here
            }
        },
        // Allows us to specify edge color (and line width) in each edge's backing data
        simpleEdgeStyles:true,
        // Use a Continuous anchor and a blank endpoint by default.
        defaults:{
            anchor:AnchorLocations.Continuous,
            endpoint:BlankEndpoint.type
        },
        events:{
            [EVENT_CANVAS_CLICK]:() => {
                toolkit.clearSelection()
            }
        }
    }

    const view = {
        nodes:{
            // abstract parent node definition - declares a tap listener
            clickable:{
                events:{
                    tap:(p) => {
                        setMsg(`You clicked on node ${p.obj.id}`)
                        toolkit.setSelection(p.obj)
                    }
                }
            },
            // definition for 'hello' nodes. Extends 'clickable' to get the tap listener.
            hello:{
                parent:"clickable",
                jsx:(ctx) => HelloComponent(ctx={ctx})
            },
            // definition for 'world' nodes. Extends 'clickable' to get the tap listener.
            world:{
                parent:"clickable",
                jsx:(ctx) => WorldComponent(ctx={ctx})
            }
        },
        edges:{
            // a default edge definition. Declares an arrow overlay at its tip and extracts 'label' from
            // edge data and displays it as a label overlay (by default at location 0.5)
            [DEFAULT]:{
                overlays:[
                    {
                        type:ArrowOverlay.type,
                        options:{
                            location: 1
                        }
                    }
                ],
                label:"{{label}}"
            }
        }
    }


    useEffect(() => {



        toolkit.load({
            data:{
                nodes:[
                    { id:"1", type:"hello", label:"Hello", left:50, top:50 },
                    { id:"2", type:"world", label:"World", left:350, top:50 }
                ],
                edges:[
                    { source:"1", target:"2", data:{label:"a label", color:"purple"} }
                ]
            }
        })
    }, [])


    return <div style={{width:"100%",height:"100%",display:"flex"}}>
                <div className="jtk-demo-canvas">
                <div className="hello-world-message">{msg}</div>
                    <JsPlumbToolkitSurfaceComponent renderParams={renderParams} toolkit={toolkit} view={view} ref={ surfaceComponent }/>
                </div>
            </div>
}

// apps/hello-world/vue3/src/components/HelloWorld.vue
<script>

    import { AbsoluteLayout, BlankEndpoint,
        DEFAULT, AnchorLocations, ArrowOverlay, EVENT_CANVAS_CLICK
    } from "@jsplumbtoolkit/browser-ui"

    import { defineComponent } from "vue"

    import HelloComponent from './HelloComponent.vue'
    import WorldComponent from './WorldComponent.vue'

    let toolkitComponent
    let toolkit
    let surface

    export default defineComponent({
        name:"hello-world",
        mounted() {
            toolkitComponent = this.$refs.toolkitComponent;
            toolkit = toolkitComponent.toolkit;
            surface = toolkitComponent.surface;

            toolkit.load({
                data:{
                    nodes:[
                        { id:"1", type:"hello", label:"Hello", left:50, top:50 },
                        { id:"2", type:"world", label:"World", left:350, top:50 }
                    ],
                    edges:[
                        { source:"1", target:"2", data:{label:"a label", color:"purple"} }
                    ]
                }
            })
        },
        data:function() {
            return { msg:'' }
        },
        methods:{
            click:function(obj) {
                this.msg = `You clicked on node ${obj.id}`
            },
            view:function() {
                return {
                    nodes:{
                        clickable:{
                            events:{
                                tap:(p) => {
                                    this.click(p.obj)
                                    toolkit.setSelection(p.obj)
                                }
                            }
                        },
                        hello:{
                            parent:"clickable",
                            component:HelloComponent
                        },
                        world:{
                            parent:"clickable",
                            component:WorldComponent
                        }
                    },
                    edges:{
                        // a default edge definition. Declares an arrow overlay at its tip and extracts 'label' from
                        // edge data and displays it as a label overlay (by default at location 0.5)
                        [DEFAULT]:{
                            overlays:[
                                {
                                    type:ArrowOverlay.type,
                                    options:{
                                        location: 1
                                    }
                                }
                            ],
                            label:"{{label}}"
                        }
                    }
                }
            },
            renderParams:function() {
                return {
                    layout:{
                        // there are several layouts that ship with the toolkit.
                        type:AbsoluteLayout.type,
                        options:{
                            //... if your chosen layout is configurable, options go here
                        }
                    },
                    // Allows us to specify edge color (and line width) in each edge's backing data
                    simpleEdgeStyles:true,
                    // Use a Continuous anchor and a blank endpoint by default.
                    defaults:{
                        anchor:AnchorLocations.Continuous,
                        endpoint:BlankEndpoint.type
                    },
                    events:{
                        [EVENT_CANVAS_CLICK]:() => {
                            toolkit.clearSelection()
                            this.msg = ''
                        }
                    }
                }
            }
        }
    })

</script>

<template>

    <div id="container">
        <div class="msg">{{msg}}</div>
    <jsplumb-toolkit ref="toolkitComponent"
                     surface-id="surfaceId"
                     v-bind:render-params="this.renderParams()"
                     v-bind:view="this.view()">

    </jsplumb-toolkit>

    </div>

</template>

<style scoped="true">
    .msg {
        position:absolute;
        left:1rem;
        top:1rem;
    }
</style>
