// apps/flowchart-builder/vue3/src/components/Inspector.vue
<template>
    <div ref="container">

        <h1 v-if="currentType===''"></h1>

        <div v-if="currentType === 'Node'" class="jtk-inspector jtk-node-inspector">
            <div class="jtk-inspector-section">
                <div>Text</div>
                <input type="text" jtk-att="text" jtk-focus/>
            </div>

            <div class="jtk-inspector-section">
                <div>Fill</div>
                <input type="color" jtk-att="fill"/>
            </div>

            <div class="jtk-inspector-section">
                <div>Color</div>
                <input type="color" jtk-att="textColor"/>
            </div>

            <div class="jtk-inspector-section">
                <div>Outline</div>
                <input type="color" jtk-att="outline"/>
            </div>
        </div>

        <div v-if="currentType === 'Edge'" class="jtk-inspector jtk-edge-inspector">
            <div class="jtk-inspector-section">
                <div>Label</div>
                <input type="text" jtk-att="label"/>
            </div>
            <div class="jtk-inspector-section">
                <div>Line style</div>
                <!--jtk-line-style current="{{lineStyle}}" jtk-att="lineStyle"></jtk-line-style-->
            </div>

            <div class="jtk-inspector-section">
                <div>Color</div>
                <input type="color" jtk-att="color"/>
            </div>
        </div>


    </div>
</template>
<script>

    import {loadSurface} from "@jsplumbtoolkit/browser-ui-vue3";
    import { Inspector } from "@jsplumbtoolkit/browser-ui"

    import { nextTick } from "vue"

    export default {
        data:() => {
            return { currentType:'' }
        },
        props:{
            surfaceId:String
        },
        mounted() {
            const self = this
            loadSurface(this.surfaceId, (surface) => {

                // create an inspector and give it the container element
                // and the surface.

                new Inspector({
                    container:this.$refs.container,
                    surface,
                    _renderEmptyContainer:() => this.currentType = '',
                    _refresh:(obj, cb) => {
                        this.currentType = obj.objectType
                        nextTick(cb)
                    }
                })
            })
        }
    }
</script>

// apps/flowchart-builder/react-app/src/InspectorComponent.js
import React, {useEffect, useRef, useState} from "react";

import { Node, Edge, Inspector} from "@jsplumbtoolkit/browser-ui"

export default function InspectorComponent({surface}) {

    const container = useRef(null)
    const [currentType, setCurrentType] = useState('')

    useEffect(() => {

        new Inspector({
            container:container.current,
            surface,
            _renderEmptyContainer:() => setCurrentType(''),
            _refresh:(obj, cb) => {
                setCurrentType(obj.objectType)
                // next tick
                setTimeout(cb)
            }
        })

    })

    return <div ref={container}>

    { currentType === Node.objectType &&
        <div className="jtk-inspector jtk-node-inspector">
            <div className="jtk-inspector-section">
            <div>Text</div>
                <input type="text" jtk-att="text" jtk-focus/>
            </div>

            <div className="jtk-inspector-section">
                <div>Fill</div>
                <input type="color" jtk-att="fill"/>
            </div>

            <div className="jtk-inspector-section">
                <div>Color</div>
                <input type="color" jtk-att="textColor"/>
            </div>

            <div className="jtk-inspector-section">
                <div>Outline</div>
                <input type="color" jtk-att="outline"/>
            </div>
        </div>
    }

    { currentType === Edge.objectType &&
        <div className="jtk-inspector jtk-edge-inspector">
            <div className="jtk-inspector-section">
                <div>Label</div>
                <input type="text" jtk-att="label"/>
            </div>
            <div className="jtk-inspector-section">
                <div>Line style</div>
            </div>
            <div className="jtk-inspector-section">
                <div>Color</div>
                <input type="color" jtk-att="color"/>
            </div>
        </div>
    }

        </div>

}
