// apps/chatbot/vue2/src/components/EndComponent.vue
<template>
    <div class="jtk-chatbot-end" data-jtk-target="true">
        <div class="jtk-delete"></div>
    </div>
</template>
<script>
    import { BaseNodeComponent } from '@jsplumbtoolkit/browser-ui-vue2'

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export default {
        mixins: [BaseNodeComponent],
        components: {},
        methods: {}
    }
</script>

// apps/chatbot/angular/src/app/end.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"

@Component({
  template:`<div class="jtk-chatbot-end" data-jtk-target="true">
    <div class="jtk-delete" (click)="removeNode()"></div>
  </div>`
})
export class EndComponent extends BaseNodeComponent {

}
