// apps/orgchart/react/src/PersonComponent.js
import React from "react"

export default function PersonComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    function getImage() {
        return `/avatars/${vertex.data.img}`
    }

    return <>
            <img src={getImage()} alt={vertex.data.name}/>
        <div>
            <strong>{vertex.data.name}</strong>
            <span>{vertex.data.title}</span>
        </div>
    </>

}

// apps/orgchart/angular/src/app/person.component.ts
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"
import {Component} from "@angular/core"

@Component({
  template:`
    <div>
      <img [src]="getImage()" [alt]="obj['name']">
      <div>
        <strong>{{obj['name']}}</strong>
        <span>{{obj['title']}}</span>
      </div>
    </div>  
  `
})
export class PersonComponent extends BaseNodeComponent {

  getImage() {
    return `/assets/avatars/${this.obj['img']}`
  }

}
