// apps/orgchart/vue2/src/components/PersonComponent.vue
<template>
    <div>
        <img :src="getImage()" :alt="obj.name"/>
        <div>
            <strong>{{obj.name}}</strong>
            <span>{{obj.title}}</span>
        </div>
    </div>
</template>
<script>
    import { BaseNodeComponent } from '@jsplumbtoolkit/browser-ui-vue2'

    export default {
        mixins: [BaseNodeComponent],
        components: {},
        methods: {
            getImage:function() {
                return `/avatars/${this.obj.img}`
            }
        }
    }
</script>

// apps/orgchart/angular/src/app/person.component.ts
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"
import {Component} from "@angular/core"

@Component({
  template:`
    <div>
      <img [src]="getImage()" [alt]="obj['name']">
      <div>
        <strong>{{obj['name']}}</strong>
        <span>{{obj['title']}}</span>
      </div>
    </div>  
  `
})
export class PersonComponent extends BaseNodeComponent {

  getImage() {
    return `/assets/avatars/${this.obj['img']}`
  }

}
