// apps/orgchart/angular/src/app/inspector.component.ts
import {AfterViewInit, ChangeDetectorRef, Component, ElementRef, EventEmitter, Input, Output} from "@angular/core"

import { Node, Base, Inspector, Vertex, Edge, JsPlumbToolkit, Surface } from "@jsplumbtoolkit/browser-ui"
import {jsPlumbService} from "@jsplumbtoolkit/browser-ui-angular"

@Component({
  template:`

    <div class="jtk-orgchart-inspector" *ngIf="current != null">
      <h1>{{current.data['name']}}</h1>
      <h2>{{current.data['title']}}</h2>
      <h5 *ngIf="reports.length > 0">Reports:</h5>
      <a *ngFor="let r of reports" class="jtk-orgchart-inspector-person" href="#" [attr.data-id]="r.data['id']" (click)="selectPerson(r)">
        <img [src]="getImage(r)" [alt]="r.data['name']"/>
        {{r.data['name']}}
      </a>
      <h5 *ngIf="manager != null">Reports to:</h5>
      <a *ngIf="manager != null" class="jtk-orgchart-inspector-person" href="#" [attr.data-id]="manager.data['id']" (click)="selectPerson(manager)">
        <img [src]="getImage(manager)" [alt]="manager.data['name']"/>
        {{manager.data['name']}}
      </a>
    </div>
    
  `,
  selector:"app-inspector"
})
export class InspectorComponent implements AfterViewInit {

  current!:Node|null
  reports:Array<Vertex> = []
  manager!:Node|null

  @Input() surfaceId!:string

  @Output() personSelected:EventEmitter<Vertex> = new EventEmitter<Vertex>()

  inspector!:Inspector

  getImage(person:Vertex) {
    return `/assets/avatars/${person.data['img']}`
  }

  retrieveDirectReports(person:Node){
    this.reports = person.getSourceEdges().map(e => e.target)
  }

  getManager(person:Node) {
    this.manager = person.getTargetEdges().map((e:Edge) => e.source)[0] as Node
  }

  selectPerson(person:Vertex) {
    this.personSelected.emit(person)
  }

  constructor(private $jsplumb:jsPlumbService, private el:ElementRef, private changeDetector:ChangeDetectorRef) { }

  ngAfterViewInit(): void {
    this.$jsplumb.getSurface(this.surfaceId, (surface) => {
      this.inspector = new Inspector({
        container:this.el.nativeElement,
        surface,
        renderEmptyContainer:() => {
          this.current = null
          this.manager = null
          this.reports.length = 0
        },
        refresh:(obj:Base, cb:() => void) => {
          this.current = obj as Node
          this.retrieveDirectReports(this.current)
          this.getManager(this.current)
          setTimeout(cb, 0)
          this.changeDetector.detectChanges()
        }
      })
    })
  }

}

// apps/orgchart/react/src/InspectorComponent.js
import React, {useEffect, useRef, useState} from "react";

import { Inspector, Vertex } from "@jsplumbtoolkit/browser-ui"
import { getSurfaceComponent} from "@jsplumbtoolkit/browser-ui-react"

export default function InspectorComponent({surfaceId, onSelect}) {

    const container = useRef(null)
    const [current, setCurrent] = useState(null)
    const [inspector, setInspector] = useState(null)
    const [manager, setManager] = useState(null)
    const [reports, setReports] = useState([])

    const initialized = useRef(false)

    function getImage(person) {
        return `/avatars/${person.data.img}`
    }

    function selectPerson(p) {
        onSelect(p)
    }

    useEffect(() => {

        if (!initialized.current) {
            initialized.current = true
            getSurfaceComponent(surfaceId, surfaceComponentRef => {
                setInspector(new Inspector({
                    container: container.current,
                    surface:surfaceComponentRef.getSurface(),
                    renderEmptyContainer: () => {
                        setCurrent(null)
                        setManager(null)
                        setReports([])
                    },
                    refresh: (obj, cb) => {
                        setCurrent(obj)
                        setManager(obj.getTargetEdges().map(e => e.source)[0])
                        setReports(obj.getSourceEdges().map(e => e.target))
                        // next tick
                        setTimeout(cb)
                    }
                }))
            })
        }

    }, [])

    function renderPersonLink(person) {
        return <a className="jtk-orgchart-inspector-person" href="#" data-id={person.data.id} onClick={() => selectPerson(person)}>
                <img src={getImage(person)} alt={person.data.name}/>
                <div>
                    {person.data.name}
                    <span>{person.data.title}</span>
                </div>
                </a>
    }


    return <div ref={container}>

        {current== null && ''}

        {current != null &&
            <div className="jtk-orgchart-inspector">

                <h1>{current.data.name}</h1>
                <h2>{current.data.title}</h2>
                {reports.length > 0 && <>
                    <h5>Reports:</h5>
                    {reports.map(r => renderPersonLink(r))}

                </>}

                {manager != null && <>

                    <h5>Reports to:</h5>
                    {renderPersonLink(manager)}

                </>}

            </div>

        }

        </div>

}
