// apps/orgchart/vue3/src/components/OrgChart.vue
<template>
    <div style="width:100%;height:100%;display:flex">
        <div class="jtk-demo-canvas">
            <jsplumb-toolkit ref="toolkitComponent"
                             surface-id="surfaceId"
                             :render-params="this.renderParams()"
                             :view="this.viewParams()"
                             url="dataset.json"
            >

            </jsplumb-toolkit>
            <jsplumb-miniview surface-id="surfaceId"></jsplumb-miniview>
        </div>
        <div class="jtk-demo-rhs">
            <div id="inspector">
                <Inspector surface-id="surfaceId" v-bind:selectPerson="selectPerson"></Inspector>
            </div>
            <div class="description">

            </div>
        </div>
    </div>
</template>
<script>

    import {defineComponent } from "vue"

    import { HierarchyLayout, BlankEndpoint, EVENT_CANVAS_CLICK, DEFAULT, PlainArrowOverlay, AnchorLocations, EVENT_TAP } from "@jsplumbtoolkit/browser-ui"

    import PersonComponent from "./PersonComponent.vue";
    import Inspector from './Inspector.vue'

    let toolkitComponent
    let toolkit
    let surface

    export default defineComponent({
        name:"orgchart",
        components: {Inspector},
        mounted() {

            toolkitComponent = this.$refs.toolkitComponent;
            toolkit = toolkitComponent.toolkit;
            surface = toolkitComponent.surface;
        },
        methods:{
            selectPerson:function(p) {
                toolkit.setSelection(p)
                surface.centerOnAndZoom(p, 0.15)
            },
            viewParams:function() {
                return {
                    nodes:{
                        [DEFAULT]:{
                            events:{
                                [EVENT_TAP]:(p) => {
                                    this.selectPerson(p.obj)
                                }
                            },
                            component:PersonComponent
                        }

                    },
                    edges:{
                        default:{
                            overlays:[
                                {
                                    type:PlainArrowOverlay.type,
                                    options:{
                                        location:1,
                                        width:10,
                                        length:10
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            renderParams:function() {
                return {
                    consumeRightClick:false,
                    elementsDraggable:false,
                    defaults:{
                        endpoint:BlankEndpoint.type,
                        anchor:AnchorLocations.ContinuousTopBottom
                    },
                    events: {
                        [EVENT_CANVAS_CLICK]: function(e) {
                            toolkit.clearSelection()
                        }
                    },
                    zoomToFit:true,
                    layout:{
                        type: HierarchyLayout.type
                    }
                }
            }
        }
    })

</script>

// apps/orgchart/react/src/OrgchartComponent.js
import React, { useEffect, useRef } from "react";
import { createRoot } from "react-dom/client";

import './orgchart.css'

import {
    newInstance,
    isPort,
    DEFAULT,
    AnchorLocations,
    BlankEndpoint,
    EVENT_CLICK,
    EVENT_TAP,
    uuid,
    HierarchyLayout,
    PlainArrowOverlay,
    EVENT_CANVAS_CLICK
} from "@jsplumbtoolkit/browser-ui"

import {
    JsPlumbToolkitSurfaceComponent,
    JsPlumbToolkitMiniviewComponent,
    ControlsComponent
} from "@jsplumbtoolkit/browser-ui-react";

import InspectorComponent from './InspectorComponent'
import PersonComponent from "./PersonComponent";

export default function OrgchartComponent(props) {

    const toolkit = newInstance()

    const surfaceComponent = useRef(null)
    const miniviewContainer = useRef(null)
    const controlsContainer = useRef(null)
    const inspectorContainer = useRef(null)

    function selectPerson(person) {
        toolkit.setSelection(person)
        surfaceComponent.current.surface.centerOnAndZoom(person, 0.15)
    }

    const renderParams = {
        consumeRightClick:false,
        elementsDraggable:false,
        defaults:{
            endpoint:BlankEndpoint.type,
            anchor:AnchorLocations.ContinuousTopBottom
        },
        events: {
            [EVENT_CANVAS_CLICK]: (e) => {
                this.toolkit.clearSelection()
            }
        },
        zoomToFit:true,
        layout:{
            type: HierarchyLayout.type
        }
    }

    const view = {
        nodes: {
            [DEFAULT]: {
                events: {
                    [EVENT_TAP]: (p) => {
                        selectPerson(p.obj)
                    }
                },
                jsx:(ctx) => <PersonComponent ctx={ctx}/>
            }

        },
        edges: {
            default: {
                overlays: [
                    {
                        type: PlainArrowOverlay.type,
                        options: {
                            location: 1,
                            width: 10,
                            length: 10
                        }
                    }
                ]
            }
        }
    }

    useEffect(() => {
        const i = createRoot(inspectorContainer.current)
        i.render(<InspectorComponent surface={surfaceComponent.current.surface} onSelect={(e) => selectPerson(e)}/>)

        const m = createRoot(miniviewContainer.current)
        m.render(<JsPlumbToolkitMiniviewComponent surface={surfaceComponent.current.surface}/>)

        toolkit.load({
            url:`/dataset.json?q=${uuid()}`
        })
    }, [])


    return <div style={{width:"100%",height:"100%",display:"flex"}}>
            <div className="jtk-demo-canvas">
                <JsPlumbToolkitSurfaceComponent renderParams={renderParams} toolkit={toolkit} view={view} ref={ surfaceComponent }/>
                <div className="miniview" ref={ miniviewContainer }/>
            </div>
            <div className="jtk-demo-rhs">
                <div id="inspector" ref={inspectorContainer}/>
            </div>
        </div>

}
