// apps/chatbot/angular/src/app/choice.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"
import { uuid } from "@jsplumbtoolkit/browser-ui"

@Component({
  template:`<div class="jtk-chatbot-choice" data-jtk-target="true">
    <div class="jtk-delete" (click)="removeNode()"></div>
    {{obj['message']}}
    <div class="jtk-choice-add" (click)="addChoice()"></div>
    <div class="jtk-chatbot-choice-option" *ngFor="let choice of obj['choices']"
         data-jtk-source="true"
         data-jtk-port-type="choice"
         [attr.data-jtk-port]="choice['id']"
         (click)="inspectChoice(choice.id)">
      {{choice['label']}}
      <div class="jtk-choice-delete" (click)="removeChoice(choice.id)"></div>
    </div>
  </div>`
})
export class ChoiceComponent extends BaseNodeComponent {

  inspectChoice(id:string) {
    this.toolkit.setSelection(this.getNode().getPort(id))
  }

  addChoice() {
    this.toolkit.setSelection(this.toolkit.addPort(this.getNode(), {
      id:uuid(),
      label:"Choice"
    }))
  }

  removeChoice(id:string) {
    this.toolkit.removePort(this.getNode(), id)
  }

}

// apps/chatbot/react/src/ChoiceComponent.js
import React from "react"

import {
    uuid
} from "@jsplumbtoolkit/browser-ui"

export default function ChoiceComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    console.log(vertex.data.choices)

    function addChoice(){
        toolkit.addPort(vertex, {
            id:uuid()
        })
    }

    function removeChoice(id) {
        toolkit.removePort(vertex, id)
    }

    function inspectChoice(id) {
        toolkit.setSelection(vertex.getPort(id))
    }

    return <div className="jtk-chatbot-choice" data-jtk-target="true">
            <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
            {vertex.data.message}
            <div className="jtk-choice-add" onClick={() => addChoice()}></div>
            {vertex.data.choices.map(c =>
                <div key={c.id} className="jtk-chatbot-choice-option" data-jtk-source="true" data-jtk-port-type="choice" data-jtk-port={c.id} onClick={() => inspectChoice(c.id)}>
                    {c.label}
                    <div className="jtk-choice-delete" onClick={() => removeChoice(c.id)}></div>
                </div>
            )}
          </div>


}
