// apps/chatbot/svelte/components/choice-component.svelte
<script>

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }

    function addChoice() {
        toolkit.addPort(vertex, {
            id:uuid(),
            label:"Choice"
        })
    }

    function removeChoice(id) {
        toolkit.removePort(vertex, id)
    }
</script>

<div class="jtk-chatbot-choice" data-jtk-target="true">
    <div class="jtk-delete" on:click={remove}></div>
    {data.message}
    <div class="jtk-choice-add" on:click={addChoice}></div>
    {#each data.choices as choice}
        <div class="jtk-chatbot-choice-option"
             data-jtk-source="true"
             data-jtk-port-type="choice"
             data-jtk-port={choice.id}>
            {choice.label}
            <div class="jtk-choice-delete" on:click={() => removeChoice(choice.id)}></div>
        </div>
    {/each}
</div>

// apps/chatbot/react/src/ChoiceComponent.js
import React from "react"

import {
    uuid
} from "@jsplumbtoolkit/browser-ui"

export default function ChoiceComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    console.log(vertex.data.choices)

    function addChoice(){
        toolkit.addPort(vertex, {
            id:uuid()
        })
    }

    function removeChoice(id) {
        toolkit.removePort(vertex, id)
    }

    function inspectChoice(id) {
        toolkit.setSelection(vertex.getPort(id))
    }

    return <div className="jtk-chatbot-choice" data-jtk-target="true">
            <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
            {vertex.data.message}
            <div className="jtk-choice-add" onClick={() => addChoice()}></div>
            {vertex.data.choices.map(c =>
                <div key={c.id} className="jtk-chatbot-choice-option" data-jtk-source="true" data-jtk-port-type="choice" data-jtk-port={c.id} onClick={() => inspectChoice(c.id)}>
                    {c.label}
                    <div className="jtk-choice-delete" onClick={() => removeChoice(c.id)}></div>
                </div>
            )}
          </div>


}
