// apps/chatbot/svelte/components/input-component.svelte
<script>
    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }
</script>

<div class="jtk-chatbot-input" data-jtk-target="true">
    <div class="jtk-delete" on:click={remove}></div>
    {data.message}
    <textarea rows="5" cols="10" placeholder="{data.prompt}"></textarea>
    <div class="connect" data-jtk-source="true"></div>
</div>

// apps/chatbot/react/src/InputComponent.js
import React from "react"

export default function InputComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    return <div className="jtk-chatbot-input" data-jtk-target="true">
        <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
    {vertex.data.message}
    <textarea rows="5" cols="10" placeholder={vertex.data.prompt}></textarea>
        <div className="connect" data-jtk-source="true"></div>
        </div>
}
