// apps/chatbot/svelte/components/message-component.svelte
<script>
    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }
</script>

<div class="jtk-chatbot-message" data-jtk-target="true">
    <div class="jtk-delete" on:click={remove}></div>
    {data.message}
    <div class="connect" data-jtk-source="true"></div>
</div>

// apps/chatbot/react/src/MessageComponent.js
import React from "react"

export default function MessageComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    return <div className="jtk-chatbot-message" data-jtk-target="true">
        <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
    {vertex.data.message}
        <div className="connect" data-jtk-source="true"></div>
        </div>

}
