// apps/schema-builder/vue2/src/components/Palette.vue
<template>
    <div class="jtk-schema-palette">
        <div class="jtk-schema-palette-item" :data-type="entry.type" title="Drag to add new" v-for="entry in data" :key="entry.type">
            {{entry.label}}
        </div>
    </div>
</template>

<script>

    import { SurfaceDrop } from '@jsplumbtoolkit/browser-ui-vue2'

    import { TABLE, VIEW } from "../constants"

    export default {
        mixins:[ SurfaceDrop ],
        data:function() {
            return {
                data:[
                    { label:"Table", type:TABLE },
                    { label:"View", type:VIEW}
                ]
            };
        }
    }

</script>

// apps/chatbot/react/src/Palette.jsx
import React from 'react';

import {SurfaceDropComponent} from '@jsplumbtoolkit/browser-ui-react';

import { nodeTypes } from "./constants";

class Palette extends SurfaceDropComponent {
    render() {
        return nodeTypes.map(nt => <div key={nt.type} className="jtk-chatbot-palette-item" data-type={nt.type}>{nt.label}</div>)
    }
}

export default Palette;
