// apps/chatbot/vue3/src/components/Palette.vue
<template>
    <div class="jtk-schema-palette">
        <div class="jtk-chatbot-palette-item" :data-type="entry.type" title="Drag to add new" v-for="entry in nodeTypes" :key="entry.type">
            {{entry.label}}
        </div>

    </div>
</template>

<script>

    import { defineComponent } from "vue";
    import { SurfaceDrop } from '@jsplumbtoolkit/browser-ui-vue3'

    import { nodeTypes } from "../constants";

    export default defineComponent({
        mixins:[ SurfaceDrop ],
        data:function() {
            return {
                nodeTypes
            }
        }
    })

</script>

// apps/chatbot/react/src/Palette.jsx
import React from 'react';

import {SurfaceDropComponent} from '@jsplumbtoolkit/browser-ui-react';

import { nodeTypes } from "./constants";

class Palette extends SurfaceDropComponent {
    render() {
        return nodeTypes.map(nt => <div key={nt.type} className="jtk-chatbot-palette-item" data-type={nt.type}>{nt.label}</div>)
    }
}

export default Palette;
