// apps/chatbot/svelte/components/start-component.svelte
<script>
    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function remove() {
        toolkit.removeNode(vertex)
    }
</script>


<div class="jtk-chatbot-start">
    <div class="jtk-delete" on:click={remove}></div>
    <div class="connect" data-jtk-source="true"/>
</div>

// apps/chatbot/react/src/StartComponent.js
import React from "react"

export default function StartComponent({ctx}) {

    const { vertex, surface, toolkit } = ctx

    return <div className="jtk-chatbot-start">
        <div className="jtk-delete" onClick={() => toolkit.removeNode(vertex)}></div>
        <div className="connect" data-jtk-source="true"></div>
        </div>
}
