// apps/chatbot/angular/src/app/input.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"

@Component({
  template:`<div class="jtk-chatbot-input" data-jtk-target="true">
    <div class="jtk-delete" (click)="removeNode()"></div>
    {{obj['message']}}
    <textarea rows="5" cols="10" placeholder="{{obj['prompt']}}"></textarea>
    <div class="connect" data-jtk-source="true"></div>
  </div>`
})
export class InputComponent extends BaseNodeComponent {

}

// apps/chatbot/vue2/src/components/InputComponent.vue
<template>
    <div class="jtk-chatbot-input" data-jtk-target="true">
        <div class="jtk-delete"></div>
        {{obj.message}}
        <textarea rows="5" cols="10" :placeholder="obj.prompt"/>
        <div class="connect" data-jtk-source="true"/>
    </div>
</template>
<script>
    import { BaseNodeComponent } from '@jsplumbtoolkit/browser-ui-vue2'

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export default {
        mixins: [BaseNodeComponent],
        components: {},
        methods: {}
    }
</script>
