// apps/chatbot/angular/src/app/message.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"

@Component({
  template:`<div class="jtk-chatbot-message" data-jtk-target="true">
    <div class="jtk-delete" (click)="removeNode()"></div>
    {{obj['message']}}
    <div class="connect" data-jtk-source="true"></div>
  </div>`
})
export class MessageComponent extends BaseNodeComponent { }

// apps/chatbot/vue2/src/components/MessageComponent.vue
<template>
    <div class="jtk-chatbot-message" data-jtk-target="true">
        <div class="jtk-delete"></div>
        {{obj.message}}
        <div class="connect" data-jtk-source="true"/>
    </div>
</template>
<script>
    import { BaseNodeComponent } from '@jsplumbtoolkit/browser-ui-vue2'

    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export default {
        mixins: [BaseNodeComponent],
        components: {},
        methods: {}
    }
</script>
