// feature-demos/groups/svelte/GroupComponent.svelte
<script>
    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export let data;
    export let toolkit;
    export let surface;
    export let vertex;

    function removeGroup() {
        toolkit.removeGroup(vertex, true)
    }

</script>

<div data-jtk-target="true">
    <div class="group-title">
        {vertex.data.title}
        <button class="expand" on:click={() => surface.toggleGroup(vertex)}></button>
        <button class="group-delete" on:click={() => removeGroup()}></button>
    </div>
    <div data-jtk-group-content="true"></div>
    <div class="group-connect connect" data-jtk-source="true">
        <i class="fa fa-chain"></i>
    </div>
</div>

// feature-demos/groups/angular/src/app/group.component.ts
import {Component} from "@angular/core"
import {BaseNodeComponent} from "@jsplumbtoolkit/browser-ui-angular"



@Component({
  template:`<div data-jtk-target="true">
    <div class="group-title">
      {{obj['title']}}
      <button class="expand" (click)="this.toggleGroup()"></button>
      <button class="group-delete" (click)="this.removeNode()"></button>
    </div>
    <div data-jtk-group-content="true"></div>
    <div class="group-connect connect" data-jtk-source="true">
      <i class="fa fa-chain"></i>
    </div>
  </div>`
})
export class GroupComponent extends BaseNodeComponent {

  toggleGroup() {
    this.surface.toggleGroup(this.getNode().id)
  }
}
