// apps/schema-builder/react-app/src/ViewComponent.js
import React from "react"


export default function ViewComponent({ctx}) {
    const { vertex, surface, toolkit } = ctx

    function deleteView() {
        toolkit.removeNode(vertex)
    }

    function editView() {
        toolkit.setSelection(vertex)
    }

    return (<div className="jtk-schema-view jtk-schema-element">
            <div className="jtk-schema-element-name">
                <div className="jtk-schema-view-delete jtk-schema-delete jtk-schema-delete-vertex" title="Delete view" onClick={() => deleteView()}/>
                <span>{vertex.data.name}</span>
                <div className="jtk-schema-buttons">
                    <div className="jtk-schema-edit-name jtk-schema-edit" title="Edit view" onClick={() => editView() }/>
                </div>
            </div>
            <div className="jtk-schema-view-details">{vertex.data.query}</div>
    </div>)
}

// apps/schema-builder/vue2/src/components/ViewComponent.vue
<template>
    <div class="jtk-schema-view jtk-schema-element">
        <div class="jtk-schema-element-name">
            <div class="jtk-schema-view-delete jtk-schema-delete jtk-schema-delete-vertex" title="Delete view" v-on:click="deleteView()"></div>
            <span>{{obj.name}}</span>
            <div class="jtk-schema-buttons">
                <div class="jtk-schema-edit-name jtk-schema-edit" title="Edit view" v-on:click="editView()"></div>
            </div>
        </div>
        <div class="jtk-schema-view-details">{{obj.query}}</div>
    </div>
</template>
<script>

    import { BaseNodeComponent } from '@jsplumbtoolkit/browser-ui-vue2'
    import ColumnComponent from './ColumnComponent.vue'

    import { COLUMN } from '../constants'
    import { datatypes } from "../definitions";
    import { uuid } from "@jsplumbtoolkit/browser-ui"

    export default {
        mixins:[BaseNodeComponent],
        methods:{
            deleteView:function(){
                this.getToolkit().removeNode(this.getNode())
            },
            editView:function() {
                this.getToolkit().setSelection(this.getNode())
            }
        }
    }
</script>
