// apps/flowchart-builder/vue3/src/components/Inspector.vue
<template>
    <div ref="container">

        <h1 v-if="currentType===''"></h1>

        <div v-if="currentType === 'Node'" class="jtk-inspector jtk-node-inspector">
            <div>Text</div>
            <input type="text" jtk-att="text" jtk-focus/>

            <div>Fill</div>
            <input type="color" jtk-att="fill"/>

            <div>Color</div>
            <input type="color" jtk-att="textColor"/>

            <div>Outline</div>
            <input type="color" jtk-att="outline"/>
        </div>

        <div v-if="currentType === 'Edge'" class="jtk-inspector jtk-edge-inspector">
            <div>Label</div>
            <input type="text" jtk-att="label"/>
            <div>Line style</div>
            <!--jtk-line-style current="{{lineStyle}}" jtk-att="lineStyle"></jtk-line-style-->
            <div>Color</div>
            <input type="color" jtk-att="color"/>
        </div>


    </div>
</template>
<script>

    import {loadSurface} from "@jsplumbtoolkit/browser-ui-vue3";
    import { Inspector } from "@jsplumbtoolkit/browser-ui"

    import { nextTick } from "vue"

    export default {
        data:() => {
            return { currentType:'' }
        },
        props:{
            surfaceId:String
        },
        mounted() {
            const self = this
            loadSurface(this.surfaceId, (surface) => {

                // create an inspector and give it the container element
                // and the surface.

                new Inspector({
                    container:this.$refs.container,
                    surface,
                    renderEmptyContainer:() => this.currentType = '',
                    refresh:(obj, cb) => {
                        this.currentType = obj.objectType
                        nextTick(cb)
                    }
                })
            })
        }
    }
</script>

// apps/flowchart-builder/react/src/InspectorComponent.js
import React, {useEffect, useRef, useState} from "react";

import { Node, Edge, Inspector} from "@jsplumbtoolkit/browser-ui"
import { EdgeTypePickerComponent } from "@jsplumbtoolkit/browser-ui-react";

export default function InspectorComponent({surface, edgeMappings}) {

    const container = useRef(null)
    const [currentType, setCurrentType] = useState('')
    const [inspector, setInspector] = useState(null)

    useEffect(() => {

        setInspector(new Inspector({
            container:container.current,
            surface,
            renderEmptyContainer:() => setCurrentType(''),
            refresh:(obj, cb) => {
                setCurrentType(obj.objectType)
                // next tick
                setTimeout(cb)
            }
        }))

    }, [])

    return <div ref={container}>

    { currentType === Node.objectType &&
        <div className="jtk-inspector jtk-node-inspector">
            <div>Text</div>
            <input type="text" jtk-att="text" jtk-focus="true"/>
            <div>Fill</div>
            <input type="color" jtk-att="fill"/>
            <div>Color</div>
            <input type="color" jtk-att="textColor"/>
            <div>Outline</div>
            <input type="color" jtk-att="outline"/>
        </div>
    }

    { currentType === Edge.objectType &&
        <div className="jtk-inspector jtk-edge-inspector">
            <div>Label</div>
            <input type="text" jtk-att="label"/>
            <div>Line style</div>
            <EdgeTypePickerComponent edgeMappings={edgeMappings} propertyName="lineStyle" inspector={inspector}/>
            <div>Color</div>
            <input type="color" jtk-att="color"/>
        </div>
    }

        </div>

}
